### ISSUE TITLE
Given address is not a valid Ethereum address

### ISSUE THREAD

**Issue by tyu1996** [harmony-one/H2O#10]
First-time trying the Harmony, attempted to follow any tutorial available on documentation.

To recreate:

1. Follow the [1-minute instructions](https://docs.harmony.one/home/developers/smart-contracts/deploy-hrc20)
2. Do the step 7
3. Receive error message:

```
root@user # truffle migrate --network testnet --reset
 
Compiling your contracts...
===========================
> Compiling ./contracts/HarmonyMintable.sol
> Artifacts written to /harmony/H20/build/contracts
> Compiled successfully using:
   - solc: 0.5.8+commit.23d335f2.Emscripten.clang

Error: Given address "one1dpm37ppsgvepjfyvsamas25md280ctgmcfjlfx" is not a valid Ethereum address.
    at Object.toChecksumAddress (/usr/lib/node_modules/truffle/build/webpack:/~/web3-utils/src/index.js:287:1)
    at Method.outputBlockFormatter (/usr/lib/node_modules/truffle/build/webpack:/~/web3-core-helpers/src/formatters.js:256:1)
    at Method.web3.eth.getBlock.method.outputFormatter (/usr/lib/node_modules/truffle/build/webpack:/packages/interface-adapter/dist/ethereum-overloads.js:37:1)
    at Method.formatOutput (/usr/lib/node_modules/truffle/build/webpack:/~/web3-core-method/src/index.js:163:1)
    at sendTxCallback (/usr/lib/node_modules/truffle/build/webpack:/~/web3-core-method/src/index.js:473:1)
    at /usr/lib/node_modules/truffle/build/webpack:/~/web3-core-requestmanager/src/index.js:147:1
    at /usr/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:112:1
    at /harmony/H20/node_modules/@harmony-js/core/src/truffleProvider.ts:155:13
    at HttpProvider.callbackHandler (/harmony/H20/node_modules/@harmony-js/network/src/providers/http.ts:135:7)
    at /harmony/H20/node_modules/@harmony-js/network/src/providers/http.ts:76:30
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Truffle v5.0.38 (core: 5.0.38)
Node v14.17.0
```

System used: Debian 10 Docker

**Comment by gupadhyaya** [comment]
@tyu1996 fixed some issues in this repository. now try `npm install` and truffle commands. thanks.

**Comment by tyu1996** [comment]
`npm install` now returns `npm ERR! Maximum call stack size exceeded`. Tried clear up npm cache, re-pull the repo and do it over again, same issue. Did you run into this issue too?

npm log, just in case you want to read: https://gist.github.com/tyu1996/302fc5aef62d4a0f6539114324a0e739
